import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Documentation hubs (2026-08):
 *   Start · Build apps · Operate · Reference
 *
 * Stable doc IDs keep existing URLs. Playbooks live under Operate.
 * Integrations appear under Build apps → Connect systems and Reference.
 */
const sidebars: SidebarsConfig = {
  startSidebar: [
    {
      type: 'category',
      label: 'Start here',
      collapsed: false,
      items: [
        'introduction/overview',
        'architecture/overview',
        'introduction/concepts',
        'glossary',
      ],
    },
    {
      type: 'category',
      label: 'Choose your path',
      collapsed: false,
      items: [
        'user/getting-started',
        'solutions/build-your-first-app',
        'solutions/runtime-vs-sdk',
        'developer/application-integration-guide',
        'getting-started/installation',
        'getting-started/quick-start',
      ],
    },
    {
      type: 'category',
      label: 'Compare',
      collapsed: true,
      items: [
        'compare/n8n-vs-qefro',
        'compare/langgraph-vs-qefro',
        'compare/chatbase-vs-qefro',
        'compare/intercom-vs-qefro',
      ],
    },
  ],

  buildAppsSidebar: [
    {
      type: 'category',
      label: 'Application integration',
      collapsed: false,
      link: {type: 'doc', id: 'developer/application-integration-guide'},
      items: [
        'developer/application-integration-guide',
        'developer/README',
        'developer/getting-started',
        'developer/integration-models',
        'developer/external-sdk-connection',
        'developer/managed-marketplace-app',
        'developer/sdk-application-development',
        'developer/qefro-protocol',
        'developer/tools',
        'developer/authentication',
        'developer/tenancy-and-workspaces',
        'developer/storage',
        'developer/customer-hub',
        'developer/organization',
        'developer/marketing',
        'developer/workflows',
        'developer/deployment/external-and-managed',
        'developer/marketplace-publishing',
        'developer/testing',
        'developer/security',
        'developer/troubleshooting',
        'developer/migration-external-to-managed',
      ],
    },
    {
      type: 'category',
      label: 'Get started',
      collapsed: false,
      link: {type: 'doc', id: 'solutions/overview'},
      items: [
        'solutions/overview',
        'solutions/runtime-vs-sdk',
        'solutions/build-your-first-app',
        'solutions/scaffold',
        'solutions/quickstart',
        'solutions/managed-apps',
        'solutions/architecture',
      ],
    },
    {
      type: 'category',
      label: 'Ship to catalog',
      collapsed: false,
      items: [
        'solutions/publishing',
        'solutions/installation',
        'solutions/marketplace',
        'solutions/packaging',
        'solutions/validation',
        'solutions/security',
      ],
    },
    {
      type: 'category',
      label: 'Platform capabilities',
      collapsed: false,
      items: [
        'solutions/customer-hub',
        'solutions/marketing',
        'solutions/organization-workflows',
        'solutions/managed-storage',
        'solutions/capabilities',
      ],
    },
    {
      type: 'category',
      label: 'Package UI',
      collapsed: true,
      items: [
        'solutions/manifest',
        'solutions/themes',
        'solutions/navigation',
        'solutions/pages',
        'solutions/layouts',
        {
          type: 'category',
          label: 'Widgets',
          collapsed: true,
          items: [
            'solutions/widgets/metric',
            'solutions/widgets/table',
            'solutions/widgets/chart',
            'solutions/widgets/markdown',
            'solutions/widgets/form',
            'solutions/widgets/timeline',
          ],
        },
        'solutions/sources',
        'solutions/events',
        'solutions/workflows',
        'solutions/assets',
        'solutions/connectors',
      ],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsed: false,
      items: [
        'solutions/examples/restaurant-pro-runtime',
        'solutions/examples/real-estate-runtime',
        'solutions/examples/shopify-runtime',
        'solutions/examples/restaurant-pro',
        'solutions/examples/clinic-pro',
        'solutions/examples/salon-pro',
        'solutions/examples/marketing-lab',
      ],
    },
    {
      type: 'category',
      label: 'Connect systems',
      collapsed: true,
      link: {type: 'doc', id: 'business-tools/index'},
      items: [
        'business-tools/index',
        'business-tools/rest-vs-sdk',
        'business-tools/rest-openapi',
        'business-tools/backend-sdk',
        'guides/register-sdk-business-tools',
        'developer/external-sdk-connection',
        'developer/application-integration-guide',
        'guides/connect-rest-apis',
        'guides/import-openapi',
        'integrations/overview',
        'developer/concepts/connectors',
      ],
    },
    'solutions/troubleshooting',
  ],

  operateSidebar: [
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'user/getting-started',
        'guides/build-ai-customer-support',
        'user/how-to/create-ai-agent',
        'user/how-to/configure-whatsapp',
        'user/how-to/connect-shopify',
      ],
    },
    {
      type: 'category',
      label: 'Workspaces & agents',
      collapsed: false,
      items: [
        'user/workspaces/overview',
        'platform/ai-workspaces',
        'user/agents/overview',
        'platform/customer-ai',
        'platform/employee-ai',
        'guides/create-employee-ai',
      ],
    },
    {
      type: 'category',
      label: 'People & knowledge',
      collapsed: false,
      items: [
        'user/people/overview',
        'solutions/customer-hub',
        'user/knowledge-base/overview',
        'platform/knowledge-platform',
        'concepts/hybrid-rag',
      ],
    },
    {
      type: 'category',
      label: 'Channels & conversations',
      collapsed: true,
      items: [
        'user/channels/overview',
        'user/channels/website-widget',
        'user/channels/whatsapp',
        'user/channels/api',
        'guides/deploy-website-widget',
        'guides/deploy-whatsapp-ai',
        'user/conversations/overview',
      ],
    },
    {
      type: 'category',
      label: 'Apps & marketplace',
      collapsed: false,
      items: [
        'solutions/marketplace',
        'solutions/installation',
        'user/how-to/track-orders',
        'user/how-to/add-approval-workflow',
      ],
    },
    {
      type: 'category',
      label: 'Approvals & analytics',
      collapsed: true,
      items: [
        'user/approvals/overview',
        'guides/run-business-flows',
        'user/analytics/overview',
        'platform/analytics',
        'user/billing/overview',
      ],
    },
    {
      type: 'category',
      label: 'Administration',
      collapsed: true,
      items: [
        'user/administration/overview',
        'platform/organizations',
        'platform/teams',
        'platform/rbac',
        'guides/configure-rbac',
        'platform/custom-domains',
        'platform/branding',
        'guides/enable-custom-domains',
      ],
    },
    {
      type: 'category',
      label: 'Recipes',
      collapsed: true,
      link: {type: 'doc', id: 'solutions/playbooks'},
      items: [
        'solutions/customer-support',
        'solutions/whatsapp-commerce',
        'solutions/order-tracking',
        'solutions/abandoned-cart',
        'solutions/appointment-booking',
        'solutions/lead-qualification',
        'solutions/refund-automation',
        'solutions/conversational-commerce',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      collapsed: true,
      items: [
        'security/overview',
        'security/tenant-isolation',
        'security/authentication-and-access',
        'security/encryption',
        'security/secrets',
        'security/network-and-egress',
        'security/data-handling',
        'security/application-security',
        'security/audit-logs',
        'security/vulnerability-disclosure',
        'security/compliance',
      ],
    },
  ],

  referenceSidebar: [
    'reference/overview',
    {
      type: 'category',
      label: 'API reference',
      collapsed: false,
      items: [
        'developer/api-reference/overview',
        'api/authentication',
        'api/rest-apis',
        'api/webhooks',
        'api/rate-limits',
        'api/error-codes',
        'api/examples',
      ],
    },
    {
      type: 'category',
      label: 'SDK reference',
      collapsed: false,
      items: [
        'api/sdks',
        'developer/sdk/javascript',
        'developer/sdk/python',
        'developer/sdk/rust',
        'business-tools/backend-sdk',
        'business-tools/parameters-reference',
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      collapsed: false,
      items: [
        'integrations/overview',
        'integrations/shopify/overview',
        'integrations/woocommerce/overview',
        'integrations/odoo/overview',
        'integrations/erpnext/overview',
        'integrations/hubspot/overview',
        'integrations/stripe/overview',
        'integrations/razorpay/overview',
        'integrations/zendesk/overview',
        'reference/connector-reference',
      ],
    },
    {
      type: 'category',
      label: 'Schemas & config',
      collapsed: false,
      items: [
        'reference/event-reference',
        'reference/environment-variables',
        'reference/configuration',
        'reference/cli',
      ],
    },
    {
      type: 'category',
      label: 'Runtime concepts',
      collapsed: true,
      items: [
        'developer/concepts/runtime',
        'developer/concepts/events',
        'developer/concepts/flows',
        'developer/concepts/tools',
        'developer/concepts/connectors',
        'business-tools/runtime',
        'developer/quick-start',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: true,
      items: [
        'architecture/overview',
        'introduction/architecture',
        'concepts/multi-tenant-ai-architecture',
      ],
    },
    {
      type: 'category',
      label: 'Compare',
      collapsed: true,
      items: [
        'compare/n8n-vs-qefro',
        'compare/langgraph-vs-qefro',
        'compare/chatbase-vs-qefro',
        'compare/intercom-vs-qefro',
        'compare/zendesk-vs-qefro',
        'compare/freshworks-vs-qefro',
        'compare/customgpt-vs-qefro',
        'compare/copilot-studio-vs-qefro',
      ],
    },
    {
      type: 'category',
      label: 'Security reference',
      collapsed: true,
      items: [
        'security/overview',
        'security/tenant-isolation',
        'security/authentication-and-access',
        'security/encryption',
        'security/secrets',
        'security/network-and-egress',
        'security/data-handling',
        'security/application-security',
        'security/audit-logs',
        'security/vulnerability-disclosure',
        'security/compliance',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      collapsed: true,
      items: [
        'developer/deployment/overview',
        'developer/deployment/external-and-managed',
        'developer/self-hosting/overview',
        'platform/deployment',
        'guides/production-deployment',
        'v1-docker',
        'v1-kubernetes',
      ],
    },
    'glossary',
    'faq',
    'troubleshooting',
    'reference/changelog',
    'release-notes',
  ],
};

export default sidebars;
