import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Information architecture:
 * Introduction · User Guide · Developer Guide · Integrations · Solutions · Reference
 *
 * Deep technical pages remain under concepts/, platform/, business-tools/, guides/,
 * api/, security/ and are linked from the audience hubs (stable URLs).
 */
const sidebars: SidebarsConfig = {
  userSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      collapsed: false,
      items: [
        'introduction/overview',
        'introduction/architecture',
        'introduction/concepts',
        'glossary',
      ],
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'user/getting-started',
        'getting-started/installation',
        'getting-started/quick-start',
        'guides/build-ai-customer-support',
      ],
    },
    {
      type: 'category',
      label: 'Workspaces',
      collapsed: true,
      items: ['user/workspaces/overview', 'platform/ai-workspaces'],
    },
    {
      type: 'category',
      label: 'Agents',
      collapsed: true,
      items: [
        'user/agents/overview',
        'platform/customer-ai',
        'platform/employee-ai',
        'guides/create-employee-ai',
      ],
    },
    {
      type: 'category',
      label: 'Knowledge Base',
      collapsed: true,
      items: [
        'user/knowledge-base/overview',
        'platform/knowledge-platform',
        'concepts/hybrid-rag',
      ],
    },
    {
      type: 'category',
      label: 'Channels',
      collapsed: true,
      items: [
        'user/channels/overview',
        'user/channels/website-widget',
        'user/channels/whatsapp',
        'user/channels/api',
        'guides/deploy-website-widget',
        'guides/deploy-whatsapp-ai',
      ],
    },
    {
      type: 'category',
      label: 'Conversations',
      collapsed: true,
      items: ['user/conversations/overview'],
    },
    {
      type: 'category',
      label: 'Approvals',
      collapsed: true,
      items: ['user/approvals/overview', 'guides/run-business-flows'],
    },
    {
      type: 'category',
      label: 'Analytics',
      collapsed: true,
      items: ['user/analytics/overview', 'platform/analytics'],
    },
    {
      type: 'category',
      label: 'Billing',
      collapsed: true,
      items: ['user/billing/overview'],
    },
    {
      type: 'category',
      label: 'Administration',
      collapsed: true,
      items: [
        'user/administration/overview',
        'platform/organizations',
        'platform/teams',
        'platform/rbac',
        'guides/configure-rbac',
        'platform/custom-domains',
        'platform/branding',
        'guides/enable-custom-domains',
      ],
    },
    {
      type: 'category',
      label: 'Security',
      collapsed: true,
      items: [
        'security/overview',
        'security/tenant-isolation',
        'security/secrets',
        'security/audit-logs',
        'security/compliance',
      ],
    },
  ],

  developerSidebar: [
    {
      type: 'category',
      label: 'Quick Start',
      collapsed: false,
      items: ['developer/quick-start', 'guides/register-sdk-business-tools'],
    },
    {
      type: 'category',
      label: 'SDK',
      collapsed: false,
      items: [
        'developer/sdk/javascript',
        'developer/sdk/python',
        'developer/sdk/rust',
        'business-tools/backend-sdk',
      ],
    },
    {
      type: 'category',
      label: 'Concepts',
      collapsed: false,
      items: [
        'developer/concepts/runtime',
        'developer/concepts/events',
        'developer/concepts/flows',
        'developer/concepts/tools',
        'developer/concepts/connectors',
        'developer/concepts/middleware',
        'developer/concepts/approvals',
        'developer/concepts/challenges',
        'developer/concepts/memory',
        'business-tools/runtime',
        'concepts/business-actions',
        'concepts/multi-tenant-ai-architecture',
        'concepts/ai-agent-security',
      ],
    },
    {
      type: 'category',
      label: 'Business Tools',
      collapsed: true,
      link: {type: 'doc', id: 'business-tools/index'},
      items: [
        'business-tools/index',
        'business-tools/rest-vs-sdk',
        'business-tools/rest-openapi',
        'business-tools/authentication',
        'business-tools/identity-forwarding',
        'business-tools/identity-resolution',
        'business-tools/challenge-resume',
        'business-tools/mixed-integrations',
        'business-tools/parameters-reference',
        'business-tools/examples',
        'guides/connect-rest-apis',
        'guides/import-openapi',
        'guides/secure-business-actions',
      ],
    },
    {
      type: 'category',
      label: 'Flows',
      collapsed: true,
      items: [
        'guides/define-business-flows',
        'guides/run-business-flows',
        'guides/event-driven-triggers',
      ],
    },
    {
      type: 'category',
      label: 'Events',
      collapsed: true,
      items: [
        'developer/events/overview',
        'guides/event-driven-triggers',
        'reference/event-reference',
      ],
    },
    {
      type: 'category',
      label: 'Webhooks',
      collapsed: true,
      items: ['developer/webhooks/overview', 'api/webhooks'],
    },
    {
      type: 'category',
      label: 'Schedules',
      collapsed: true,
      items: ['developer/schedules/overview'],
    },
    {
      type: 'category',
      label: 'Channels',
      collapsed: true,
      items: ['developer/channels/overview'],
    },
    {
      type: 'category',
      label: 'Observability',
      collapsed: true,
      items: ['developer/observability/overview'],
    },
    {
      type: 'category',
      label: 'Deployment',
      collapsed: true,
      items: [
        'developer/deployment/overview',
        'developer/self-hosting/overview',
        'platform/deployment',
        'guides/production-deployment',
        'v1-docker',
        'v1-kubernetes',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: true,
      items: [
        'developer/api-reference/overview',
        'api/authentication',
        'api/rest-apis',
        'api/sdks',
        'api/webhooks',
        'api/rate-limits',
        'api/error-codes',
        'api/examples',
      ],
    },
  ],

  integrationsSidebar: [
    'integrations/overview',
    {
      type: 'category',
      label: 'Shopify',
      collapsed: true,
      items: ['integrations/shopify/overview'],
    },
    {
      type: 'category',
      label: 'WooCommerce',
      collapsed: true,
      items: ['integrations/woocommerce/overview'],
    },
    {
      type: 'category',
      label: 'Odoo',
      collapsed: true,
      items: ['integrations/odoo/overview'],
    },
    {
      type: 'category',
      label: 'ERPNext',
      collapsed: true,
      items: ['integrations/erpnext/overview'],
    },
    {
      type: 'category',
      label: 'HubSpot',
      collapsed: true,
      items: ['integrations/hubspot/overview'],
    },
    {
      type: 'category',
      label: 'Stripe',
      collapsed: true,
      items: ['integrations/stripe/overview'],
    },
    {
      type: 'category',
      label: 'Razorpay',
      collapsed: true,
      items: ['integrations/razorpay/overview', 'api/webhooks'],
    },
    {
      type: 'category',
      label: 'Zendesk',
      collapsed: true,
      items: ['integrations/zendesk/overview'],
    },
    'developer/concepts/connectors',
    'reference/connector-reference',
    'guides/event-driven-triggers',
  ],

  solutionsSidebar: [
    'solutions/overview',
    'solutions/customer-support',
    'solutions/order-tracking',
    'solutions/abandoned-cart',
    'solutions/appointment-booking',
    'solutions/refund-automation',
    'solutions/conversational-commerce',
    {
      type: 'category',
      label: 'Related guides',
      collapsed: true,
      items: [
        'guides/build-ai-customer-support',
        'guides/event-driven-triggers',
        'guides/secure-business-actions',
      ],
    },
  ],

  referenceSidebar: [
    'reference/overview',
    'reference/cli',
    'reference/environment-variables',
    'reference/configuration',
    'reference/event-reference',
    'reference/connector-reference',
    {
      type: 'category',
      label: 'API',
      collapsed: true,
      items: [
        'api/authentication',
        'api/rest-apis',
        'api/sdks',
        'api/webhooks',
        'api/rate-limits',
        'api/error-codes',
        'api/examples',
      ],
    },
    'api/error-codes',
    'glossary',
    'faq',
    'troubleshooting',
    'reference/changelog',
    'release-notes',
    {
      type: 'category',
      label: 'Compare',
      collapsed: true,
      items: [
        'compare/chatbase-vs-qefro',
        'compare/intercom-vs-qefro',
        'compare/zendesk-vs-qefro',
        'compare/freshworks-vs-qefro',
        'compare/customgpt-vs-qefro',
        'compare/copilot-studio-vs-qefro',
      ],
    },
    {
      type: 'category',
      label: 'Security reference',
      collapsed: true,
      items: [
        'security/overview',
        'security/tenant-isolation',
        'security/secrets',
        'security/audit-logs',
        'security/compliance',
      ],
    },
  ],
};

export default sidebars;
